PATH="$HOME/bin:$HOME/go/bin:/opt/homebrew/bin${PATH:+:${PATH}}"

BREW_DIR=$(brew --prefix)
DOTFILES_DIR="$HOME/.dotfiles"

# Load aws env
# . "$DOTFILES_DIR/aws/env.zsh"
export AWS_PROFILE=saml

# Load tokens
export NPM_TOKEN=$(security find-generic-password -w -l NPM_TOKEN)

# Set up fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fd --type f'

# Load grc aliases
[[ -s "$BREW_DIR/etc/grc.zsh" ]] && source "$BREW_DIR/etc/grc.zsh"

# Load asdf
[[ -f "$HOME/.asdf/asdf.sh" ]] && source $HOME/.asdf/asdf.sh

# Load z
[[ -f "$BREW_DIR/etc/profile.d/z.sh" ]] && source $BREW_DIR/etc/profile.d/z.sh

# Load custom aliases
[[ -f "$HOME/.zsh_aliases" ]] && source $HOME/.zsh_aliases

# Load fzf
. "$DOTFILES_DIR/fzf/fzf.zsh"

# Pure
fpath=($HOME/.zsh/pure $fpath)

# Functions
fpath=($HOME/.zsh/functions $fpath)

# Load completion functions
fpath=($ASDF_DIR/completions $fpath)
autoload -Uz compinit
compinit

# Load prompt
autoload -U promptinit; promptinit
prompt pure
alias update-nvim-nightly='asdf uninstall neovim nightly && asdf install neovim nightly'
